# Generated by Django 3.2.7 on 2022-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Newscontent',
        # ),
        # migrations.RenameField(
        #      model_name='intelligentstrategy',
        #      old_name='intelligent_strategy_id',
        #      new_name='intelligent_strategy_id',
        #  ),
        #migrations.RenameField(
        #    model_name='technicalstrategry',
        #    old_name='technical_strategry_name',
        #    new_name='technical_strategy_id',
        #),
        migrations.AddField(
            model_name='intelligentstrategy',
            name='intelligent_strategy_long_short',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='intelligentstrategy',
            name='intelligent_strategy_money_manage',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='intelligentstrategy',
            name='intelligent_strategy_stop_pl',
            field=models.CharField(default='', max_length=11),
        ),
        # migrations.AddField(
        #     model_name='news',
        #     name='news_category',
        #     field=models.BigIntegerField(blank=True, null=True),
        # ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalstrategry',
            name='technical_strategy_long_short',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='technicalstrategry',
            name='technical_strategy_money_manage',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='technicalstrategry',
            name='technical_strategy_stop_lp',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='intelligentstrategy',
            name='intelligent_strategy_algorithm',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_area',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technicalstrategry',
            name='technical_strategry_enter',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='technicalstrategry',
            name='technical_strategry_exit',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='intelligentstrategy',
            unique_together={('intelligent_strategy_id', 'member_id')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalstrategry',
            unique_together={('technical_strategy_id', 'member')},
        ),
        migrations.RemoveField(
            model_name='intelligentstrategy',
            name='intelligent_strategy_end',
        ),
        migrations.RemoveField(
            model_name='intelligentstrategy',
            name='intelligent_strategy_enter',
        ),
        migrations.RemoveField(
            model_name='intelligentstrategy',
            name='intelligent_strategy_exit',
        ),
        migrations.RemoveField(
            model_name='intelligentstrategy',
            name='intelligent_strategy_index1',
        ),
        migrations.RemoveField(
            model_name='intelligentstrategy',
            name='intelligent_strategy_index2',
        ),
        migrations.RemoveField(
            model_name='intelligentstrategy',
            name='intelligent_strategy_start',
        ),
        migrations.RemoveField(
            model_name='technicalstrategry',
            name='technical_strategry_index1',
        ),
        migrations.RemoveField(
            model_name='technicalstrategry',
            name='technical_strategry_index2',
        ),
    ]
