# Generated by Django 3.2.7 on 2022-04-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220426_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newscontent',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_title', models.TextField(blank=True, null=True)),
                ('news_content', models.TextField(blank=True, null=True)),
                ('news_time', models.TextField(blank=True, null=True)),
                ('news_author', models.TextField(blank=True, null=True)),
                ('news_photo', models.TextField(blank=True, null=True)),
                ('news_area', models.BigIntegerField(blank=True, null=True)),
                ('member_id', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'news_content',
                'managed': True,
            },
        ),
    ]
