# Generated by Django 3.2.7 on 2022-04-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_newscontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntelligentStrategy',
        ),
    ]
