# Generated by Django 3.2.7 on 2022-04-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_intelligentstrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligentStrategy',
            fields=[
                ('intelligent_strategy_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('intelligent_strategy_algorithm', models.CharField(max_length=10)),
                ('intelligent_strategy_long_short', models.CharField(default='', max_length=11)),
                ('intelligent_strategy_money_manage', models.CharField(default='', max_length=11)),
                ('intelligent_strategy_stop_pl', models.CharField(default='', max_length=11)),
                ('futures', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.futures')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.member')),
            ],
            options={
                'db_table': 'intelligent_strategy',
                'managed': True,
                'unique_together': {('intelligent_strategy_id', 'member_id')},
            },
        ),
    ]
