# Generated by Django 3.2.9 on 2022-05-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_intelligentstrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactionrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, max_length=50, null=True)),
                ('futeres_id', models.CharField(blank=True, max_length=10, null=True)),
                ('futures_name', models.CharField(blank=True, max_length=10, null=True)),
                ('record', models.IntegerField(blank=True, null=True)),
                ('buy_qty', models.IntegerField(blank=True, null=True)),
                ('buy_mon', models.IntegerField(blank=True, null=True)),
                ('buy_time', models.DateTimeField(blank=True, null=True)),
                ('sell_qty', models.IntegerField(blank=True, null=True)),
                ('sell_mon', models.IntegerField(blank=True, null=True)),
                ('sell_time', models.DateTimeField(blank=True, null=True)),
                ('return_rate', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'transactionRecord',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='corn',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dcboard',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='futures',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='indexclass',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='intelligentstrategy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='minidow',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mininastaq',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='minirussell',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='minisp',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mtx',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='newscontent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='soy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='te',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='technicalstrategry',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tf',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tx',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='wheat',
            options={'managed': False},
        ),
    ]
