# Generated by Django 4.0.4 on 2022-05-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_transactionrecord_alter_class_options_and_more'),
    ]
    operations = [
       migrations.CreateModel(
            name='Newscontent',
            fields=[
                ('news_id',models.IntegerField(primary_key=True, serialize=False)),
                ('news_title', models.TextField(blank=True, null=True)),
                ('news_content', models.TextField(blank=True, null=True)),
                ('news_time', models.TextField(blank=True, null=True)),
                ('news_author', models.TextField(blank=True, null=True)),
                ('news_photo', models.TextField(blank=True, null=True)),
                ('news_area', models.BigIntegerField(blank=True, null=True)),
                ('member_id', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'news_content',
                'managed': True,
            },
        ),
    ]
