# Generated by Django 3.2.7 on 2022-05-10 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_newscontent'),
        ('myapp', '0011_newscontent'),
    ]

    operations = [
    ]
